# Generated by Django 4.2 on 2023-06-20 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('EQUITY', 'Equity'), ('FUTURE', 'Future'), ('OPTION', 'Option')], max_length=50)),
                ('expiry', models.DateField(null=True)),
                ('option_type', models.CharField(choices=[('CE', 'Ce'), ('PE', 'Pe')], max_length=5, null=True)),
                ('strike_price', models.FloatField(null=True)),
                ('lot_size', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KiteInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_token', models.BigIntegerField()),
                ('exchange_token', models.BigIntegerField()),
                ('tradingsymbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_price', models.FloatField(null=True)),
                ('expiry', models.DateField(null=True)),
                ('strike_price', models.FloatField(null=True)),
                ('tick_size', models.FloatField(null=True)),
                ('lot_size', models.IntegerField(null=True)),
                ('instrument_type', models.CharField(max_length=100, null=True)),
                ('segment', models.CharField(max_length=100, null=True)),
                ('exchange', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='long_short_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('current_iv', models.FloatField(null=True)),
                ('avg_iv', models.FloatField(null=True)),
                ('high_iv', models.FloatField(null=True)),
                ('low_iv', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200, null=True)),
                ('long_moves_prev', models.FloatField(null=True)),
                ('short_moves_prev', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pair_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol_1', models.CharField(max_length=200)),
                ('iv_1', models.FloatField(null=True)),
                ('symbol_2', models.CharField(max_length=200)),
                ('iv_2', models.FloatField(null=True)),
                ('avg_iv_1', models.FloatField(null=True)),
                ('avg_iv_2', models.FloatField(null=True)),
                ('movement_1', models.FloatField(null=True)),
                ('movement_2', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='scanner_table_skew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('spread', models.CharField(max_length=200, null=True)),
                ('z_score', models.FloatField(null=True)),
                ('straddle_skew', models.FloatField(null=True)),
                ('strike_1', models.FloatField(null=True)),
                ('strike_2', models.FloatField(null=True)),
                ('exit', models.FloatField(null=True)),
                ('entry', models.FloatField(null=True)),
                ('r2', models.FloatField(null=True)),
                ('correlation', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isin', models.CharField(max_length=20, null=True)),
                ('code', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('STOCK', 'Stock'), ('INDEX', 'Index')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='skew_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('put_b_value', models.FloatField(null=True)),
                ('call_b_value', models.FloatField(null=True)),
                ('put_call_b_value', models.FloatField(null=True)),
                ('put_call_a_value', models.FloatField(null=True)),
                ('put_straddle_skew', models.FloatField(null=True)),
                ('call_straddle_skew', models.FloatField(null=True)),
                ('put_call_straddle_skew', models.FloatField(null=True)),
                ('put_call_straddle_kurt', models.FloatField(null=True)),
                ('R2_put_call', models.FloatField(null=True)),
                ('R2_call', models.FloatField(null=True)),
                ('strike_1_put_call', models.FloatField(null=True)),
                ('strike_2_put_call', models.FloatField(null=True)),
                ('strike_1_call', models.FloatField(null=True)),
                ('strike_2_call', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vol_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('current_iv', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='live_before_df',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('ticker', models.CharField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('open_interest', models.IntegerField(null=True)),
                ('instrument_type', models.CharField(null=True)),
                ('strike_price', models.FloatField(null=True)),
                ('expiry', models.CharField(null=True)),
                ('live_update_df', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='websocket_trial.live_before_df')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('KITE', 'Kite'), ('IIFL', 'Iifl')], default='KITE', max_length=10)),
                ('tradingsymbol', models.CharField(max_length=50)),
                ('token', models.BigIntegerField(null=True)),
                ('exchange_token', models.BigIntegerField(null=True)),
                ('exchange', models.CharField(max_length=50, null=True)),
                ('data', models.JSONField(default=dict)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='websocket_trial.instrument')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='websocket_trial.security'),
        ),
    ]
