# Generated by Django 4.2 on 2023-06-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair_table',
            name='movement_1',
        ),
        migrations.RemoveField(
            model_name='pair_table',
            name='movement_2',
        ),
        migrations.AddField(
            model_name='pair_table',
            name='long_movement',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pair_table',
            name='short_movement',
            field=models.FloatField(null=True),
        ),
    ]
