# Generated by Django 4.2 on 2023-06-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0004_pair_table_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='skew_table',
            name='call_strikes_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_table',
            name='put_call_strikes_ratio',
            field=models.FloatField(null=True),
        ),
    ]
