# Generated by Django 4.2 on 2023-07-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0005_skew_table_call_strikes_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner_table_skew',
            name='current_iv',
            field=models.FloatField(null=True),
        ),
    ]
