# Generated by Django 4.2 on 2023-07-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0007_remove_scanner_table_skew_correlation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol_table',
            name='fut_close',
            field=models.FloatField(null=True),
        ),
    ]
