# Generated by Django 4.2 on 2023-07-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0009_skew_table_strike_1_put_skew_table_strike_2_put'),
    ]

    operations = [
        migrations.CreateModel(
            name='idv_cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('long_move', models.FloatField(default=0)),
                ('full_move', models.FloatField(default=0)),
                ('current_fut', models.FloatField(default=0)),
                ('current_vol', models.FloatField(null=True)),
            ],
        ),
    ]
