# Generated by Django 4.2 on 2023-08-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0010_idv_cal'),
    ]

    operations = [
        migrations.CreateModel(
            name='move_iv_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('current_iv', models.FloatField(null=True)),
                ('move_based_iv', models.FloatField(null=True)),
                ('high_iv', models.FloatField(null=True)),
                ('low_iv', models.FloatField(null=True)),
            ],
        ),
    ]
