# Generated by Django 4.2 on 2023-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0011_move_iv_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='next_expiry_live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('ticker', models.CharField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('open_interest', models.IntegerField(null=True)),
                ('instrument_type', models.CharField(null=True)),
                ('strike_price', models.FloatField(null=True)),
                ('expiry', models.CharField(null=True)),
            ],
        ),
    ]
