# Generated by Django 4.2 on 2023-09-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0012_next_expiry_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='move_iv_tb',
            name='current_call_iv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='move_iv_tb',
            name='current_put_iv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='move_iv_tb',
            name='iv_diff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vol_table',
            name='current_atm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vol_table',
            name='current_call_iv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vol_table',
            name='current_put_iv',
            field=models.FloatField(null=True),
        ),
    ]
