# Generated by Django 4.2 on 2023-09-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0013_move_iv_tb_current_call_iv_move_iv_tb_current_put_iv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner_table_skew',
            name='num',
            field=models.FloatField(null=True),
        ),
    ]
