# Generated by Django 4.2 on 2023-09-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0014_scanner_table_skew_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='skew_scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.FloatField(null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('spread', models.CharField(max_length=200, null=True)),
                ('z_score', models.FloatField(null=True)),
                ('straddle_skew', models.FloatField(null=True)),
                ('strike_1', models.FloatField(null=True)),
                ('strike_2', models.FloatField(null=True)),
                ('exit', models.FloatField(null=True)),
                ('entry', models.FloatField(null=True)),
                ('current_iv', models.FloatField(null=True)),
                ('correlation_last_day', models.FloatField(null=True)),
                ('correlation_last_week', models.FloatField(null=True)),
                ('r2', models.FloatField(null=True)),
            ],
        ),
    ]
