# Generated by Django 4.2 on 2023-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0015_skew_scanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='move_iv_tb',
            name='call_std',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='move_iv_tb',
            name='four_leg_std',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='move_iv_tb',
            name='put_std',
            field=models.FloatField(null=True),
        ),
    ]
