# Generated by Django 4.2 on 2023-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0017_forward_vol_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_skew_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('b_value', models.FloatField(null=True)),
                ('a_value', models.FloatField(null=True)),
                ('put_skew_strike', models.FloatField(null=True)),
                ('call_skew_strike', models.FloatField(null=True)),
                ('put_kurt_strike', models.FloatField(null=True)),
                ('call_kurt_strike', models.FloatField(null=True)),
                ('atm_strike', models.FloatField(null=True)),
                ('put_skew_iv', models.FloatField(null=True)),
                ('call_skew_iv', models.FloatField(null=True)),
                ('put_kurt_iv', models.FloatField(null=True)),
                ('call_kurt_iv', models.FloatField(null=True)),
                ('atm_iv', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='long_short_tb',
            old_name='avg_iv',
            new_name='hv_current',
        ),
        migrations.RenameField(
            model_name='long_short_tb',
            old_name='benchmark_iv',
            new_name='risk_prem',
        ),
        migrations.RenameField(
            model_name='long_short_tb',
            old_name='high_iv',
            new_name='risk_prem_historical',
        ),
        migrations.RenameField(
            model_name='long_short_tb',
            old_name='long_moves_prev',
            new_name='skew',
        ),
        migrations.RemoveField(
            model_name='long_short_tb',
            name='low_iv',
        ),
        migrations.RemoveField(
            model_name='long_short_tb',
            name='short_moves_prev',
        ),
        migrations.RemoveField(
            model_name='long_short_tb',
            name='signal',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='correlation_last_day',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='correlation_last_week',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='current_iv',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='exit',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='num',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='r2',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='spread',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='straddle_skew',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='strike_1',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='strike_2',
        ),
        migrations.RemoveField(
            model_name='skew_scanner',
            name='z_score',
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='a_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='atm_iv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='atm_strike',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='b_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='call_iv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='call_strike',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='put_iv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='put_strike',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='time',
            field=models.TimeField(max_length=200, null=True),
        ),
    ]
