# Generated by Django 4.2 on 2023-10-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0018_new_skew_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skew_scanner',
            name='spread',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='z',
            field=models.FloatField(null=True),
        ),
    ]
