# Generated by Django 4.2 on 2023-10-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0019_skew_scanner_spread_skew_scanner_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='long_short_tb',
            name='rp_diff',
            field=models.FloatField(null=True),
        ),
    ]
