# Generated by Django 4.2 on 2023-10-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0020_long_short_tb_rp_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_skew_table',
            name='down_rem',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='up_rem',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='down_rem',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='up_rem',
            field=models.FloatField(null=True),
        ),
    ]
