# Generated by Django 4.2 on 2023-10-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0021_new_skew_table_down_rem_new_skew_table_up_rem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live_before_df',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='live_before_df',
            name='open_interest',
        ),
        migrations.RemoveField(
            model_name='live_before_df',
            name='volume',
        ),
    ]
