# Generated by Django 4.2 on 2023-10-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0022_remove_live_before_df_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_skew_table',
            name='p_c_skew',
            field=models.FloatField(null=True),
        ),
    ]
