# Generated by Django 4.2 on 2023-10-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0023_new_skew_table_p_c_skew'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_skew_table',
            name='kurt_atm_diff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='skew_atm_diff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='skew',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='skew_scanner',
            name='target',
            field=models.FloatField(null=True),
        ),
    ]
