# Generated by Django 4.2 on 2023-10-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0024_new_skew_table_kurt_atm_diff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair_table',
            name='target',
            field=models.FloatField(null=True),
        ),
    ]
