# Generated by Django 4.2 on 2023-10-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0025_pair_table_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair_table',
            name='current_diff',
            field=models.FloatField(null=True),
        ),
    ]
