# Generated by Django 4.2 on 2023-10-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0026_pair_table_current_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_skew_table',
            name='down_rem',
        ),
        migrations.RemoveField(
            model_name='new_skew_table',
            name='up_rem',
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='call_a_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='call_b_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='call_skew_atm_diff1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='call_skew_atm_diff2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='call_skew_iv1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='call_skew_iv2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='call_skew_strike1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='call_skew_strike2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='put_a_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='put_b_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='put_skew_atm_diff1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='put_skew_atm_diff2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='put_skew_iv1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='put_skew_iv2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='put_skew_strike1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='new_skew_table',
            name='put_skew_strike2',
            field=models.FloatField(null=True),
        ),
    ]
