# Generated by Django 4.2 on 2023-10-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0027_remove_new_skew_table_down_rem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='long_short_tb',
            name='vol_ratio',
            field=models.FloatField(null=True),
        ),
    ]
