# Generated by Django 4.2 on 2023-10-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0028_long_short_tb_vol_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='weekly_expiry_live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('ticker', models.CharField(null=True)),
                ('close', models.FloatField(null=True)),
                ('instrument_type', models.CharField(null=True)),
                ('strike_price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='weekly_skew_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('b_value', models.FloatField(null=True)),
                ('a_value', models.FloatField(null=True)),
                ('put_b_value', models.FloatField(null=True)),
                ('put_a_value', models.FloatField(null=True)),
                ('call_b_value', models.FloatField(null=True)),
                ('call_a_value', models.FloatField(null=True)),
                ('put_skew_strike', models.FloatField(null=True)),
                ('call_skew_strike', models.FloatField(null=True)),
                ('put_skew_strike1', models.FloatField(null=True)),
                ('put_skew_strike2', models.FloatField(null=True)),
                ('call_skew_strike1', models.FloatField(null=True)),
                ('call_skew_strike2', models.FloatField(null=True)),
                ('put_kurt_strike', models.FloatField(null=True)),
                ('call_kurt_strike', models.FloatField(null=True)),
                ('atm_strike', models.FloatField(null=True)),
                ('put_skew_iv', models.FloatField(null=True)),
                ('call_skew_iv', models.FloatField(null=True)),
                ('put_skew_iv1', models.FloatField(null=True)),
                ('put_skew_iv2', models.FloatField(null=True)),
                ('call_skew_iv1', models.FloatField(null=True)),
                ('call_skew_iv2', models.FloatField(null=True)),
                ('put_kurt_iv', models.FloatField(null=True)),
                ('call_kurt_iv', models.FloatField(null=True)),
                ('atm_iv', models.FloatField(null=True)),
                ('p_c_skew', models.FloatField(null=True)),
                ('skew_atm_diff', models.FloatField(null=True)),
                ('kurt_atm_diff', models.FloatField(null=True)),
                ('put_skew_atm_diff1', models.FloatField(null=True)),
                ('put_skew_atm_diff2', models.FloatField(null=True)),
                ('call_skew_atm_diff1', models.FloatField(null=True)),
                ('call_skew_atm_diff2', models.FloatField(null=True)),
            ],
        ),
    ]
