# Generated by Django 4.2 on 2023-10-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0029_weekly_expiry_live_weekly_skew_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='idv_cal',
            name='bench_vol',
            field=models.FloatField(null=True),
        ),
    ]
