# Generated by Django 4.2 on 2023-11-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0031_forward_vol_tb_fair_vol'),
    ]

    operations = [
        migrations.CreateModel(
            name='put_call_OI_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('put_OI_val', models.FloatField(null=True)),
                ('call_OI_val', models.FloatField(null=True)),
                ('put_call_ratio', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='idv_cal',
            name='day_theta',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='live_before_df',
            name='open_interest',
            field=models.IntegerField(null=True),
        ),
    ]
