# Generated by Django 4.2 on 2023-11-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0032_put_call_oi_tb_idv_cal_day_theta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward_vol_tb',
            name='hv_current',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='forward_vol_tb',
            name='ivp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='long_short_tb',
            name='fair_vol',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='long_short_tb',
            name='ivp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pair_table',
            name='hv_current_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pair_table',
            name='hv_current_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pair_table',
            name='ivp1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pair_table',
            name='ivp2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pair_table',
            name='z_score',
            field=models.FloatField(null=True),
        ),
    ]
