# Generated by Django 4.2 on 2023-11-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0033_forward_vol_tb_hv_current_forward_vol_tb_ivp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='next_exp_vol_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('strike_price', models.FloatField(null=True)),
                ('instrument_type', models.CharField(null=True)),
                ('bid_iv', models.FloatField(null=True)),
                ('ask_iv', models.FloatField(null=True)),
                ('fut_close', models.FloatField(null=True)),
            ],
        ),
    ]
