# Generated by Django 4.2 on 2023-11-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0034_next_exp_vol_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='next_expiry_live',
            name='expiry',
        ),
        migrations.AddField(
            model_name='next_expiry_live',
            name='ask_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='next_expiry_live',
            name='bid_price',
            field=models.FloatField(null=True),
        ),
    ]
