# Generated by Django 4.2 on 2023-11-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0035_remove_next_expiry_live_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='next_exp_scanner_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200)),
                ('strike_price', models.FloatField(null=True)),
                ('instrument_type', models.CharField(null=True)),
                ('iv', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
            ],
        ),
    ]
