# Generated by Django 4.2 on 2023-11-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0037_long_short_tb_fwd_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair_table',
            name='fwd_iv_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pair_table',
            name='fwd_iv_2',
            field=models.FloatField(null=True),
        ),
    ]
