# Generated by Django 4.2 on 2023-12-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0039_position_fut_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='skew_scanner',
            name='ivp',
            field=models.FloatField(null=True),
        ),
    ]
