# Generated by Django 4.2 on 2023-12-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0040_skew_scanner_ivp'),
    ]

    operations = [
        migrations.CreateModel(
            name='position_tracker_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=200)),
            ],
        ),
    ]
