# Generated by Django 4.2 on 2023-12-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_trial', '0043_position_fut_tb_init_atm_iv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='overwatch_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_time', models.TimeField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200)),
                ('symbol1', models.CharField(max_length=200)),
                ('symbol2', models.CharField(max_length=200)),
                ('iv1', models.FloatField(null=True)),
                ('iv2', models.FloatField(null=True)),
                ('curr_val', models.FloatField(null=True)),
                ('curr_percentile', models.FloatField(null=True)),
                ('prev_time', models.TimeField(max_length=200, null=True)),
                ('prev_val', models.FloatField(null=True)),
                ('prev_percentile', models.FloatField(null=True)),
            ],
        ),
    ]
